### PR TITLE
Added required headers for building OpenCV

### PR DESCRIPTION
**Pull request by darosior**
Cf https://github.com/kivy-garden/garden.zbarcam/issues/20

### CODE REVIEW

**Comment by AndreMiras** [comment]
Thanks for the contribution!
I would suggest to use a dedicated patch file instead of `sed`-ing from the `Makefile`. I think having a patch file makes it easier to review/update and understand what's doing later.

Additionally I think it may requires a bit more of investigation why this is failing on your platform and not on Ubuntu Bionic 18.04 for instance. The idea is that it might be something else we're missing like, system dependency or include flag.
Could you tell us more about the platform you're running?
For records I found this resource https://stackoverflow.com/q/46884682/185510 where somebody seems to have the same issue on Ubuntu Xenial 16.04.

**Comment by darosior** [comment]
I had this issue while compiling on Debian Stretch, and a Debian(Jessie)-like.

**Comment by AndreMiras** [comment]
OK thank you I'll give that a try in a Docker env

**Comment by darosior** [comment]
> I would suggest to use a dedicated patch file instead of `sed`-ing from the `Makefile`

Which file should I patch ?

**Comment by AndreMiras** [comment]
Something like `ffmpeg_headers.patch` that's a diff between before your sed fix and after it.
Then in the `Makefile` we can `patch -p1 < ffmpeg_headers.patch`.
I can help on kivy Discord if you ping on the `#support` channel

**Comment by darosior** [comment]
Updated to use a patch file instead of sed.

**Comment by AndreMiras** [comment]
Much better thanks!
For records here are some references I saw about the issue:

- https://github.com/opencv/opencv/issues/10503
- https://stackoverflow.com/q/46884682/185510

Note that the issue was reported upstream, then closed. I'll probably just merge the patch as it is and try to apply it conditionally. Just trying to think about something more satisfying than checking the OS.
Maybe with an environment variable, I don't know. Or actually checking if that header is defined somehow.
In the meantime what is the result of the  `lsb_release -si` on Debian?

**Comment by AndreMiras** [comment]
I dig some more and I saw both `AVFMT_RAWPICTURE` and `CODEC_FLAG_GLOBAL_HEADER` are shipped as third party includes in the opencv-2.4 bundle:
```
grep -rE '#define AVFMT_RAWPICTURE|#define CODEC_FLAG_GLOBAL_HEADER' opencv-2.4*/3rdparty/
opencv-2.4.13.6/3rdparty/include/ffmpeg_/libavformat/avformat.h:#define AVFMT_RAWPICTURE    0x0020 /**< Format wants AVPicture structure for
opencv-2.4.13.6/3rdparty/include/ffmpeg_/libavcodec/avcodec.h:#define CODEC_FLAG_GLOBAL_HEADER  0x00400000 ///< Place global headers in extradata instead of every keyframe.
```
I'm not too sure why it doesn't get included on some platforms.
Both headers can also be provided by system include for instance on Ubuntu 18.04:
```
dpkg -S avformat.h avcodec.h
libavformat-dev:amd64: /usr/include/x86_64-linux-gnu/libavformat/avformat.h
libavcodec-dev:amd64: /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h
```
While I didn't have these installed for compiling opencv it might help on your case to have them.
Could you give it a try with these two and without the patch?

**Comment by darosior** [comment]
I tried first by installing related ffmpeg packages such as `libavcodec-extra`, `libavcodec58`, `libavcodec-extra58` and it didn't build.
I tried with your snippet, and it didn't work neither.
I still got the same error :
```
error: ‘CODEC_FLAG_GLOBAL_HEADER’ was not declared in this scope
```

**Pull request closed without merging**
